### ISSUE TITLE
`parameterize_class` and `super()`

### ISSUE THREAD

**Issue by couchemar** [wolever/parameterized#73]
Decorated classes fails on `super()` calls, because after decoration class instance changes to  `None`.
https://github.com/wolever/parameterized/blob/85222cfd5f93ba026a74a4726ae98d6f89fff502/parameterized/parameterized.py#L572 should returns `base_class`. 

For example:

```python
import unittest

@parameterized.parameterized_class([
    {'foo': 'bar'}
])
class Test(unittest.TestCase):

    def setUp(self):
        super(Test, self).setUp()

    def test(self):
        assert False
```

Fails with:
```
... in setUp
    super(Test, self).setUp()
TypeError: super() argument 1 must be type, not None
```

**Comment by broox** [comment]
i have run into this as well.

**Comment by wolever** [comment]
Okay, this turns out to be a bit of a fiddly issue.

Basically, the problem is:

1. `@parameterize_class` works like `@parameterized.expand`, where it creates synthetic subclasses (one per parameter) and injects them into the same namespace as the parent class.

2. This leaves the original class object lying around, and test runners will try to run tests with it.

3. But it doesn't make sense to run tests on the original class, as no parameters have been applied.

It seems like a reasonable workaround is to remove the `test_` methods from the class being parameterized, though: https://github.com/wolever/parameterized/pull/83

**Comment by wolever** [comment]
I’ve just pushed version 0.7.1 which should fix this issue 🙂
